In [1]:
import torch
import torchvision
from IPython import display
from d2l import torch as d2l

/home/zeng/anaconda3/envs/torch/lib/python3.11/site-packages/torchvision/models/detection/anchor_utils.py:63: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at /croot/pytorch_1686931851744/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device("cpu"),


In [9]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

/home/zeng/anaconda3/envs/torch/lib/python3.11/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(


In [13]:
num_input = 764
num_output = 10

w = torch.normal(0, 0.01, size=(num_input, num_output), requires_grad=True)
b = torch.zeros(num_output, requires_grad=True)

- 定义softmax

In [17]:
X = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

In [18]:
X.sum(0, keepdim=True), X.sum(1, keepdim=True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [26]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim=True)
    return X_exp /partition

In [28]:
X = torch.normal(0, 1, (2, 5))
X_prob = softmax(X)
X_prob, X_prob.sum(1)

(tensor([[0.2684, 0.1452, 0.2605, 0.2302, 0.0958],
         [0.1710, 0.4696, 0.2781, 0.0148, 0.0665]]),
 tensor([1.0000, 1.0000]))

In [30]:
def net(X):
    return softmax(torch.matmul(X.reshape((-1, W.shape[0])), W) + b)

In [31]:
def cross_entropy(y_hat, y):
    return -torch.log(y_hat[range(len(y_hat)), y]) # 交叉熵

In [36]:
y_hat = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
y = torch.tensor([0.

In [41]:
a = torch.randn(1)
a

tensor([0.6804])

In [42]:
torch.numel(a)

1

In [43]:
len(a)

1

In [49]:
d2l.evaluate_accuracy(net, )

TypeError: 'DataLoader' object is not subscriptable

In [46]:
device: torch.device = torch.device("cpu")