In [1]:
import torch

In [4]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([2, 2, 1, 2])

In [5]:
x < y

tensor([ True, False, False, False])

In [6]:
import os

In [7]:
path = os.path.join("../path/", "date", ".txt")

In [8]:
print(path)

../path/date/.txt


In [9]:
a = torch.arange(6).reshape(2,3)

In [12]:
b = torch.arange(3)
c= torch.arange(3) + 2

In [17]:
torch.dot(a, b)

RuntimeError: 1D tensors expected, but got 2D and 1D tensors

In [16]:
torch.mv(a, b)

tensor([ 5, 14])

In [19]:
import math, time
import numpy as np


In [32]:
n = 10000
a = torch.ones(n)
b = torch.ones(n)

In [21]:
type(a)

torch.Tensor

In [26]:
c = [0 for i in range(n)]
c = torch.tensor(c)
c

tensor([0, 0, 0,  ..., 0, 0, 0])

In [25]:
class Timer: #@save
    """记录多次运⾏时间"""
    def __init__(self):
        self.times = []
        self.start()
        
    def start(self):
        """启动计时器"""
        self.tik = time.time()
        
    def stop(self):
        """停⽌计时器并将时间记录在列表中"""
        self.times.append(time.time() - self.tik)
        return self.times[-1]
    
    def avg(self):
        """返回平均时间"""
        return sum(self.times) / len(self.times)
    
    def sum(self):
        """返回时间总和"""
        return sum(self.times)
    
    def cumsum(self):
        """返回累计时间"""
        return np.array(self.times).cumsum().tolist()

In [36]:
timer = Timer()
for i in range(n):
    c[i] = a[i] + b[i]
d = timer.stop()
f"{timer.stop():.5f} sec"

'0.08571 sec'

In [39]:
timer.start()
d = a + b
f"{timer.stop():.5f} sec"

'0.00140 sec'

In [37]:
f"{timer.stop():.5f} sec"

'75.94005 sec'

In [38]:
f"{timer.stop():.5f} sec"

'78.20799 sec'