In [1]:
import torch
from torch import nn

In [11]:
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__() #初始化继承层模型参数
        self.fc1 = nn.Linear(10, 20) 
        self.fc2 = nn.Linear(20, 10)

    def forward(self, x):
        x = self.fc1(x)
        x = torch.relu(x)
        x = self.fc2(x)
        return x

In [13]:
model = MyModel() # 构建一个网络

- Model()相当于调用__call__方法， 而神经网络中调用__call__方法就就相当如调用forward方法

In [14]:
input = torch.randn(1, 10)
output = model(input)

In [15]:
input

tensor([[ 0.5917,  0.6888, -0.9411,  0.9857,  1.4511, -0.4055,  1.6190, -0.1808,
          0.2162, -0.3057]])

In [31]:
class Mymodel1(nn.Module):
    def __init__(self, ):
        super(Mymodel1, self).__init__()
        self.model = None
        self.fc = nn.Linear(10, 20)

    def forward(self, x):
        x = self.model(x)
        x = self.fc(x)
        x = torch.relu(x)
        return x

    def __call__(self, x):
        self.model = MyModel()
        print("x")
        return self.forward(x)
    

In [32]:
model = Mymodel1()
output = model(input)

x


In [33]:
output

tensor([[0.0000, 0.2904, 0.0000, 0.0000, 0.0125, 0.0487, 0.0964, 0.0673, 0.0574,
         0.0000, 0.0000, 0.0718, 0.0000, 0.1382, 0.0000, 0.3417, 0.1150, 0.2751,
         0.1235, 0.0000]], grad_fn=<ReluBackward0>)

In [18]:
class Test():
    def __init__(self, in_: int = 2, out: int = 10):
        print(out)
        self.in_ = in_
    def test(self):
        print(self.in_)

In [19]:
test = Test()

10


In [20]:
test.test()

2


In [21]:
from torch.nn.modules.utils import _pair

In [22]:
_pair?

Signature: _pair(x)
Docstring: <no docstring>
File:      ~/anaconda3/envs/torch/lib/python3.11/site-packages/torch/nn/modules/utils.py
Type:      function

In [27]:
_pair((2, 5))

(2, 5)

In [35]:
import torch
from torch import nn
torch.randint(1, 5, (1, ))

tensor([1])

In [67]:
class Mymodel1(nn.Module):
    def __init(self, b = True):
        super(Mymodel, self)
        if b:
            print(1)
            self.bias = torch.randint(1, 10, (1, ))
        else:
            print(2)
            # self.register_parameter('bias', 1)
    def forward(self, x):
        return x
    

In [68]:
model = Mymodel1()

In [69]:
model(1)

1